apiVersion: kustomize.config.k8s.io/v1beta1  # apiVersion을 v1beta1로 변경
kind: Kustomization
namePrefix: prod-
resources:
  - ../../base
  - pvc.yaml
patches:
  - deployment.yaml  # patchesStrategicMerge 대신 patches 사용
  - ingress.yaml
configMapGenerator:
  - name: "82255864-configmap"
    files:
      - application.yml
images:
  - name: ce82255864acr.azurecr.io/82255864
    newTag: "202408090453"
