apiVersion: kustomize.k8s.io/v1  # 최신 API 버전으로 변경
kind: Kustomization
namePrefix: prod-
resources:
  - ../../base
  - pvc.yaml
patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml
configMapGenerator:
  - name: "82255864-configmap"
    files:
      - application.yml
images:
  - name: ce82255864acr.azurecr.io/82255864
    newTag: "202408090453"
